# Generated by Django 5.1 on 2024-08-21 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Network",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="название сети"
                    ),
                ),
                (
                    "network_type",
                    models.CharField(
                        choices=[
                            ("factory", "Завод"),
                            ("retail_network", "Розничная сеть"),
                            (
                                "individual_entrepreneur",
                                "Индивидуальный предприниматель",
                            ),
                        ],
                        max_length=50,
                        verbose_name="тип сети",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="электронная почта"),
                ),
                ("country", models.CharField(max_length=100, verbose_name="страна")),
                ("city", models.CharField(max_length=100, verbose_name="город")),
                ("street", models.CharField(max_length=100, verbose_name="улица")),
                (
                    "house_number",
                    models.CharField(max_length=10, verbose_name="номер дома/здания"),
                ),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="задолженность",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время создание"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="networks.network",
                        verbose_name="поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "сеть",
                "verbose_name_plural": "сети",
            },
        ),
    ]
